version: '3.8'

services:
  app:
    image: 'cypress/included:9.1.1'
    entrypoint: bash
    environment:
      - DISPLAY
    working_dir: /app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/app
