version: '3.8'

services:
  app:
    image: 'mcr.microsoft.com/playwright:focal'
    entrypoint: bash
    environment:
      - DISPLAY
    working_dir: /app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/app
